version: 2
updates:
  - package-ecosystem: npm
    directories:
      - '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: 'eslint'
        versions: ['>=9.0.0']
      - dependency-name: 'eslint-plugin-sonarjs'
        versions: ['>=1.0.0']
      - dependency-name: 'eslint-plugin-vitest'
        versions: ['>=0.5.0']

  - package-ecosystem: github-actions
    directories:
      - '/'
    schedule:
      interval: daily
