version: 2
updates:
  - package-ecosystem: npm
    directories:
      - '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 999

  - package-ecosystem: github-actions
    directories:
      - '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 999
