module.exports = {
  version: '0.2',
  language: 'en',
  ignorePaths: [
    '.git/',
    '.history/',
    'node_modules/',
    'coverage/',
    'dist/',
    '.next/',
    '.idea/',
    '.vscode/',
    '**/*.svg',
    '.*ignore',
    '*.tsbuildinfo',
    '.gitattributes',
    '.htmlhintrc',
    'package.json',
    'package-lock.json',
    'yarn.lock',
    'pnpm-lock.yaml',
    'CHANGELOG.md',
    'Dockerfile',
  ],
  dictionaries: [
    'user-apps',
    'user-brands',
    'user-docker',
    'user-files',
    'user-git',
    'user-nginx',
    'user-npm',
    'user-typescript',
  ],
  dictionaryDefinitions: [
    {
      name: 'user-apps',
      path: './dictionaries/apps.dic',
      addWords: true,
    },
    {
      name: 'user-brands',
      path: './dictionaries/brands.dic',
      addWords: true,
    },
    {
      name: 'user-docker',
      path: './dictionaries/docker.dic',
      addWords: true,
    },
    {
      name: 'user-files',
      path: './dictionaries/files.dic',
      addWords: true,
    },
    {
      name: 'user-git',
      path: './dictionaries/git.dic',
      addWords: true,
    },
    {
      name: 'user-nginx',
      path: './dictionaries/nginx.dic',
      addWords: true,
    },
    {
      name: 'user-npm',
      path: './dictionaries/npm.dic',
      addWords: true,
    },
    {
      name: 'user-typescript',
      path: './dictionaries/typescript.dic',
      addWords: true,
    },
  ],
};
