module.exports = {
  version: '0.1',
  language: 'en',
  words: [
    'browserslistrc',
    'builtins',
    'chunkhash',
    'commitlint',
    'commitlintrc',
    'configsrc',
    'contenthash',
    'cosmiconfig',
    'devtool',
    'dockerignore',
    'donniean',
    'editorconfig',
    'eslint',
    'eslintignore',
    'favicons',
    'gitattributes',
    'gulpfile',
    'htmlhint',
    'htmlhintrc',
    'huskyrc',
    'immer',
    'iphonex',
    'lintstagedrc',
    'miniprogram',
    'prettierignore',
    'readonly',
    'sourcemap',
    'stylelint',
    'stylelintignore',
    'stylelintrc',
    'todos',
    'webpackbar',
    'webstorm',
    'wechat',
  ],
  ignorePaths: [
    '**/.idea/**',
    '**/.vscode/**',
    '**/dist/**',
    '**/build/**',
    '**/libs/**',
    '**/*.min.*',
    '**/.gitattributes',
    '**/.gitignore',
    '**/.htmlhintrc',
    '**/package.json',
    '**/package-lock.json',
    '**/Dockerfile',
    '**/.dockerignore',
  ],
};
