import { defineConfig } from 'oxlint';

export default defineConfig({
  options: {
    typeAware: true,
    typeCheck: true,
    reportUnusedDisableDirectives: 'error',
    respectEslintDisableDirectives: false,
  },
  env: {
    builtin: true,
    node: true,
  },
  categories: {
    correctness: 'off',
    suspicious: 'off',
    pedantic: 'off',
    perf: 'off',
    style: 'off',
    restriction: 'off',
    nursery: 'off',
  },
  plugins: [
    'eslint',
    'typescript',
    'unicorn',
    'oxc',
    'import',
    'jsdoc',
    'promise',
  ],
  jsPlugins: ['eslint-plugin-sonarjs', 'eslint-plugin-unused-imports'],
  rules: {
    'no-console': [
      process.env['NODE_ENV'] === 'development' ? 'warn' : 'error',
      { allow: ['warn', 'error'] },
    ],
  },
  overrides: [
    {
      files: [
        '**/*.cjs',
        '**/.htmlvalidate.{js,mjs,cjs}',
        '**/.ncurc.{js,mjs,cjs}',
        '**/commitlint.config.{js,mjs,cjs,ts}',
        '**/cspell.config.{js,mjs,cjs,ts}',
        '**/oxlint.config.{js,mjs,cjs,ts}',
        '**/html-validate.config.{js,mjs,cjs,ts}',
        '**/i18next.config.{js,mjs,cjs,ts}',
        '**/jest.config.{js,mjs,cjs,ts}',
        '**/lint-staged.config.{js,mjs,cjs,ts}',
        '**/prettier.config.{js,mjs,cjs,ts}',
        '**/rollup.config.{js,mjs,cjs,ts}',
        '**/stylelint.config.{js,mjs,cjs,ts}',
        '**/tsup.config.{js,mjs,cjs,ts}',
        '**/vite.config.{js,mjs,cjs,ts}',
        '**/vitest.config.{js,mjs,cjs,ts}',
        'config/**/*.{js,cjs,mjs,ts}',
        'scripts/**/*.{js,cjs,mjs,ts}',
      ],
      env: {
        node: true,
      },
    },
    {
      files: ['**/*.{mjs,ts,tsx}'],
      rules: {
        'simple-import-sort/imports': 'error',
        'simple-import-sort/exports': 'error',
      },
      jsPlugins: ['eslint-plugin-simple-import-sort'],
    },
    {
      files: ['**/*.{ts,tsx}'],
      rules: {
        'no-array-constructor': 'error',
        'no-implied-eval': 'off',
        'no-unused-expressions': 'error',
        'no-useless-constructor': 'error',
        'no-throw-literal': 'off',
        'prefer-promise-reject-errors': 'off',
        'require-await': 'off',
        'typescript/await-thenable': 'error',
        'typescript/ban-ts-comment': [
          'error',
          {
            minimumDescriptionLength: 10,
          },
        ],
        'typescript/no-array-delete': 'error',
        'typescript/no-base-to-string': 'error',
        'typescript/no-confusing-void-expression': 'error',
        'typescript/no-deprecated': 'error',
        'typescript/no-duplicate-enum-values': 'error',
        'typescript/no-duplicate-type-constituents': 'error',
        'typescript/no-dynamic-delete': 'error',
        'typescript/no-empty-object-type': 'error',
        'typescript/no-explicit-any': 'error',
        'typescript/no-extra-non-null-assertion': 'error',
        'typescript/no-extraneous-class': 'error',
        'typescript/no-floating-promises': 'error',
        'typescript/no-for-in-array': 'error',
        'typescript/no-implied-eval': 'error',
        'typescript/no-invalid-void-type': 'error',
        'typescript/no-meaningless-void-operator': 'error',
        'typescript/no-misused-new': 'error',
        'typescript/no-misused-promises': 'error',
        'typescript/no-misused-spread': 'error',
        'typescript/no-mixed-enums': 'error',
        'typescript/no-namespace': 'error',
        'typescript/no-non-null-asserted-nullish-coalescing': 'error',
        'typescript/no-non-null-asserted-optional-chain': 'error',
        'typescript/no-non-null-assertion': 'error',
        'typescript/no-redundant-type-constituents': 'error',
        'typescript/no-require-imports': 'error',
        'typescript/no-this-alias': 'error',
        'typescript/no-unnecessary-boolean-literal-compare': 'error',
        'typescript/no-unnecessary-template-expression': 'error',
        'typescript/no-unnecessary-type-arguments': 'error',
        'typescript/no-unnecessary-type-assertion': 'error',
        'typescript/no-unnecessary-type-constraint': 'error',
        'typescript/no-unnecessary-type-conversion': 'error',
        'typescript/no-unnecessary-type-parameters': 'error',
        'typescript/no-unsafe-argument': 'error',
        'typescript/no-unsafe-assignment': 'error',
        'typescript/no-unsafe-call': 'error',
        'typescript/no-unsafe-declaration-merging': 'error',
        'typescript/no-unsafe-enum-comparison': 'error',
        'typescript/no-unsafe-function-type': 'error',
        'typescript/no-unsafe-member-access': 'error',
        'typescript/no-unsafe-return': 'error',
        'typescript/no-unsafe-unary-minus': 'error',
        'typescript/no-useless-default-assignment': 'error',
        'typescript/no-wrapper-object-types': 'error',
        'typescript/only-throw-error': 'error',
        'typescript/prefer-as-const': 'error',
        'typescript/prefer-literal-enum-member': 'error',
        'typescript/prefer-namespace-keyword': 'error',
        'typescript/prefer-promise-reject-errors': 'error',
        'typescript/prefer-reduce-type-parameter': 'error',
        'typescript/prefer-return-this-type': 'error',
        'typescript/related-getter-setter-pairs': 'error',
        'typescript/require-await': 'error',
        'typescript/restrict-plus-operands': [
          'error',
          {
            allowAny: false,
            allowBoolean: false,
            allowNullish: false,
            allowNumberAndString: false,
            allowRegExp: false,
          },
        ],
        'typescript/restrict-template-expressions': [
          'error',
          {
            allowAny: false,
            allowBoolean: false,
            allowNever: false,
            allowNullish: false,
            allowNumber: false,
            allowRegExp: false,
          },
        ],
        'typescript/return-await': ['error', 'error-handling-correctness-only'],
        'typescript/triple-slash-reference': 'error',
        'typescript/unbound-method': 'error',
        'typescript/unified-signatures': 'error',
        'typescript/use-unknown-in-catch-callback-variable': 'error',
        'no-empty-function': 'error',
        'typescript/adjacent-overload-signatures': 'error',
        'typescript/array-type': 'error',
        'typescript/ban-tslint-comment': 'error',
        'typescript/class-literal-property-style': 'error',
        'typescript/consistent-generic-constructors': 'error',
        'typescript/consistent-indexed-object-style': 'error',
        'typescript/consistent-type-assertions': 'error',
        'typescript/consistent-type-definitions': 'error',
        'typescript/dot-notation': 'error',
        'typescript/no-confusing-non-null-assertion': 'error',
        'typescript/no-inferrable-types': 'error',
        'typescript/non-nullable-type-assertion-style': 'error',
        'typescript/prefer-find': 'error',
        'typescript/prefer-for-of': 'error',
        'typescript/prefer-function-type': 'error',
        'typescript/prefer-includes': 'error',
        'typescript/prefer-nullish-coalescing': 'error',
        'typescript/prefer-regexp-exec': 'error',
        'typescript/prefer-string-starts-ends-with': 'error',
        'typescript/consistent-type-exports': 'error',
        'typescript/consistent-type-imports': 'error',
      },
    },
    {
      files: ['src/**'],
      rules: {
        'react/display-name': 'error',
        'react/jsx-key': 'error',
        'react/jsx-no-comment-textnodes': 'error',
        'react/jsx-no-duplicate-props': 'error',
        'react/jsx-no-target-blank': 'error',
        'react/jsx-no-undef': 'error',
        'react/no-children-prop': 'error',
        'react/no-danger-with-children': 'error',
        'react/no-direct-mutation-state': 'error',
        'react/no-find-dom-node': 'error',
        'react/no-is-mounted': 'error',
        'react/no-render-return-value': 'error',
        'react/no-string-refs': 'error',
        'react/no-unescaped-entities': 'error',
        'react/no-unknown-property': 'error',
        'react/no-unsafe': 'off',
        'react/react-in-jsx-scope': 'off',
        'react/rules-of-hooks': 'error',
        'react/exhaustive-deps': 'warn',
        'jsx-a11y/alt-text': 'error',
        'jsx-a11y/anchor-ambiguous-text': 'off',
        'jsx-a11y/anchor-has-content': 'error',
        'jsx-a11y/anchor-is-valid': 'error',
        'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
        'jsx-a11y/aria-props': 'error',
        'jsx-a11y/aria-proptypes': 'error',
        'jsx-a11y/aria-role': 'error',
        'jsx-a11y/aria-unsupported-elements': 'error',
        'jsx-a11y/autocomplete-valid': 'error',
        'jsx-a11y/click-events-have-key-events': 'error',
        'jsx-a11y/control-has-associated-label': [
          'off',
          {
            ignoreElements: [
              'audio',
              'canvas',
              'embed',
              'input',
              'textarea',
              'tr',
              'video',
            ],
            ignoreRoles: [
              'grid',
              'listbox',
              'menu',
              'menubar',
              'radiogroup',
              'row',
              'tablist',
              'toolbar',
              'tree',
              'treegrid',
            ],
            includeRoles: ['alert', 'dialog'],
          },
        ],
        'jsx-a11y/heading-has-content': 'error',
        'jsx-a11y/html-has-lang': 'error',
        'jsx-a11y/iframe-has-title': 'error',
        'jsx-a11y/img-redundant-alt': 'error',
        'jsx-a11y/interactive-supports-focus': [
          'error',
          {
            tabbable: [
              'button',
              'checkbox',
              'link',
              'searchbox',
              'spinbutton',
              'switch',
              'textbox',
            ],
          },
        ],
        'jsx-a11y/label-has-associated-control': 'error',
        'jsx-a11y/media-has-caption': 'error',
        'jsx-a11y/mouse-events-have-key-events': 'error',
        'jsx-a11y/no-access-key': 'error',
        'jsx-a11y/no-autofocus': 'error',
        'jsx-a11y/no-distracting-elements': 'error',
        'jsx-a11y/no-interactive-element-to-noninteractive-role': [
          'error',
          {
            tr: ['none', 'presentation'],
            canvas: ['img'],
          },
        ],
        'jsx-a11y/no-noninteractive-element-interactions': [
          'error',
          {
            handlers: [
              'onClick',
              'onError',
              'onLoad',
              'onMouseDown',
              'onMouseUp',
              'onKeyPress',
              'onKeyDown',
              'onKeyUp',
            ],
            alert: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
            body: ['onError', 'onLoad'],
            dialog: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
            iframe: ['onError', 'onLoad'],
            img: ['onError', 'onLoad'],
          },
        ],
        'jsx-a11y/no-noninteractive-element-to-interactive-role': [
          'error',
          {
            ul: [
              'listbox',
              'menu',
              'menubar',
              'radiogroup',
              'tablist',
              'tree',
              'treegrid',
            ],
            ol: [
              'listbox',
              'menu',
              'menubar',
              'radiogroup',
              'tablist',
              'tree',
              'treegrid',
            ],
            li: [
              'menuitem',
              'menuitemradio',
              'menuitemcheckbox',
              'option',
              'row',
              'tab',
              'treeitem',
            ],
            table: ['grid'],
            td: ['gridcell'],
            fieldset: ['radiogroup', 'presentation'],
          },
        ],
        'jsx-a11y/no-noninteractive-tabindex': [
          'error',
          {
            tags: [],
            roles: ['tabpanel'],
            allowExpressionValues: true,
          },
        ],
        'jsx-a11y/no-redundant-roles': 'error',
        'jsx-a11y/no-static-element-interactions': [
          'error',
          {
            allowExpressionValues: true,
            handlers: [
              'onClick',
              'onMouseDown',
              'onMouseUp',
              'onKeyPress',
              'onKeyDown',
              'onKeyUp',
            ],
          },
        ],
        'jsx-a11y/role-has-required-aria-props': 'error',
        'jsx-a11y/role-supports-aria-props': 'error',
        'jsx-a11y/scope': 'error',
        'jsx-a11y/tabindex-no-positive': 'error',
        'react/only-export-components': [
          'error',
          {
            allowConstantExport: true,
          },
        ],
        '@tanstack/query/exhaustive-deps': 'error',
        '@tanstack/query/no-rest-destructuring': 'warn',
        '@tanstack/query/stable-query-client': 'error',
        '@tanstack/query/no-unstable-deps': 'error',
        '@tanstack/query/infinite-query-property-order': 'error',
        '@tanstack/query/no-void-query-fn': 'error',
        '@tanstack/query/mutation-property-order': 'error',
        'i18next/no-literal-string': ['error'],
      },
      plugins: ['react', 'jsx-a11y'],
      jsPlugins: ['@tanstack/eslint-plugin-query', 'eslint-plugin-i18next'],
      env: {
        browser: true,
      },
      globals: {
        $: 'readonly',
        $_: 'readonly',
        $$: 'readonly',
        $0: 'readonly',
        $1: 'readonly',
        $2: 'readonly',
        $3: 'readonly',
        $4: 'readonly',
        $x: 'readonly',
        chrome: 'readonly',
        clear: 'readonly',
        copy: 'readonly',
        debug: 'readonly',
        dir: 'readonly',
        dirxml: 'readonly',
        getEventListeners: 'readonly',
        inspect: 'readonly',
        keys: 'readonly',
        monitor: 'readonly',
        monitorEvents: 'readonly',
        profile: 'readonly',
        profileEnd: 'readonly',
        queryObjects: 'readonly',
        table: 'readonly',
        undebug: 'readonly',
        unmonitor: 'readonly',
        unmonitorEvents: 'readonly',
        values: 'readonly',
      },
    },
    {
      files: ['server/**'],
      rules: {
        'node/no-exports-assign': 'error',
      },
      globals: {
        __dirname: 'off',
        __filename: 'off',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        atob: 'readonly',
        Blob: 'readonly',
        BroadcastChannel: 'readonly',
        btoa: 'readonly',
        Buffer: 'readonly',
        ByteLengthQueuingStrategy: 'readonly',
        clearImmediate: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        CloseEvent: 'readonly',
        CompressionStream: 'readonly',
        console: 'readonly',
        CountQueuingStrategy: 'readonly',
        crypto: 'readonly',
        Crypto: 'readonly',
        CryptoKey: 'readonly',
        CustomEvent: 'readonly',
        DecompressionStream: 'readonly',
        DOMException: 'readonly',
        Event: 'readonly',
        EventTarget: 'readonly',
        exports: 'off',
        fetch: 'readonly',
        File: 'readonly',
        FormData: 'readonly',
        global: 'readonly',
        Headers: 'readonly',
        MessageChannel: 'readonly',
        MessageEvent: 'readonly',
        MessagePort: 'readonly',
        module: 'off',
        navigator: 'readonly',
        Navigator: 'readonly',
        performance: 'readonly',
        Performance: 'readonly',
        PerformanceEntry: 'readonly',
        PerformanceMark: 'readonly',
        PerformanceMeasure: 'readonly',
        PerformanceObserver: 'readonly',
        PerformanceObserverEntryList: 'readonly',
        PerformanceResourceTiming: 'readonly',
        process: 'readonly',
        queueMicrotask: 'readonly',
        ReadableByteStreamController: 'readonly',
        ReadableStream: 'readonly',
        ReadableStreamBYOBReader: 'readonly',
        ReadableStreamBYOBRequest: 'readonly',
        ReadableStreamDefaultController: 'readonly',
        ReadableStreamDefaultReader: 'readonly',
        Request: 'readonly',
        require: 'off',
        Response: 'readonly',
        setImmediate: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
        structuredClone: 'readonly',
        SubtleCrypto: 'readonly',
        TextDecoder: 'readonly',
        TextDecoderStream: 'readonly',
        TextEncoder: 'readonly',
        TextEncoderStream: 'readonly',
        TransformStream: 'readonly',
        TransformStreamDefaultController: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        WebAssembly: 'readonly',
        WebSocket: 'readonly',
        WritableStream: 'readonly',
        WritableStreamDefaultController: 'readonly',
        WritableStreamDefaultWriter: 'readonly',
      },
      plugins: ['node'],
      env: {
        es2024: true,
        node: true,
      },
    },
    {
      files: ['**/tests/**', '**/*.test.{js,jsx,ts,tsx}'],
      rules: {
        'vitest/expect-expect': 'error',
        'vitest/no-commented-out-tests': 'error',
        'vitest/no-conditional-expect': 'error',
        'vitest/no-disabled-tests': 'warn',
        'vitest/no-focused-tests': 'error',
        'vitest/no-identical-title': 'error',
        'vitest/no-import-node-test': 'error',
        'vitest/no-interpolation-in-snapshots': 'error',
        'vitest/no-mocks-import': 'error',
        'vitest/no-standalone-expect': 'error',
        'vitest/no-unneeded-async-expect-function': 'error',
        'vitest/prefer-called-exactly-once-with': 'error',
        'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
        'vitest/valid-describe-callback': 'error',
        'vitest/valid-expect': 'error',
        'vitest/valid-expect-in-promise': 'error',
        'vitest/valid-title': 'error',
      },
      plugins: ['vitest'],
    },
  ],
});
