// This file is automatically generated by i18next-cli. Do not edit manually.
import type Resources from './resources';

declare module 'i18next' {
  interface CustomTypeOptions {
    enableSelector: true;
    defaultNS: 'common';
    resources: Resources;
  }
}
