// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  common: {
    hello: 'Hello {{entity}}';
  };
  errors: {
    'app.actions.retry': 'Retry';
    'app.title': 'Something went wrong';
    'notFound.actions.back': 'Back to Home';
    'notFound.title': '404 - Not Found';
    'route.title': 'An unexpected error occurred';
  };
  glossary: {
    'term.react': 'React';
  };
}

export default Resources;
