/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as ErrorsNotFoundRouteImport } from './../routes/errors/not-found'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsNotFoundRoute = ErrorsNotFoundRouteImport.update({
  id: '/errors/not-found',
  path: '/errors/not-found',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/errors/not-found': typeof ErrorsNotFoundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/errors/not-found': typeof ErrorsNotFoundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/errors/not-found': typeof ErrorsNotFoundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/errors/not-found'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/errors/not-found'
  id: '__root__' | '/' | '/errors/not-found'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorsNotFoundRoute: typeof ErrorsNotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/not-found': {
      id: '/errors/not-found'
      path: '/errors/not-found'
      fullPath: '/errors/not-found'
      preLoaderRoute: typeof ErrorsNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorsNotFoundRoute: ErrorsNotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
