name: CI

on:
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
      - name: Install Dependencies
        run: npm ci
      # Linters
      - name: Prettier
        run: npm run lint:prettier
      - name: tsc
        run: npm run lint:tsc
      - name: ESLint
        run: npm run lint:eslint
      - name: Stylelint
        run: npm run lint:stylelint
      - name: HTMLHint
        run: npm run lint:htmlhint
      - name: markdownlint
        run: npm run lint:markdownlint
      - name: CSpell
        run: npm run lint:cspell
      - name: Sort Package.json
        run: npm run lint:sort-package-json

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
