name: Demo

on:
  workflow_dispatch:
  schedule:
    - cron: '50 3 * * *'

jobs:
  test-ci:
    runs-on: ubuntu-latest
    steps:
      - name: demo
        run: |
          echo "github.event_name: ${{ github.event_name }}"
