name: Dependencies Bump

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  bump:
    uses: donniean/collections/.github/workflows/dependencies.bump.yml@main
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
