name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set Docker Image Tag
        # cSpell: ignore elif
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_type }}" == "branch" ]]; then
            if [[ "${{ github.ref_name }}" == "main" ]]; then
              echo "TAG=latest" >> $GITHUB_ENV
            else
              echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
            fi
          fi

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: donniean/react-app:${{ env.TAG }}
          push: true
