name: Pull Requests Auto-Merge
on:
  pull_request:

jobs:
  auto-merge:
    permissions:
      contents: write
      pull-requests: write
    uses: donniean/hub/.github/workflows/pull-requests.auto-merge.yaml@main
