name: Pull Requests Auto-Update
on:
  push:

jobs:
  auto-update:
    uses: donniean/hub/.github/workflows/pull-requests.auto-update.yaml@main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
